modLoader="javafml"
loaderVersion="[43,)"
license="Apache License version 2.0"

[[mods]]
modId="money"
version="4.0.0"
displayName="Money Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="hyper, MCreator"
description='''
A mod for all your money needs
'''

[[dependencies.money]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




